In [ ]:
import torch
import numpy as np

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Thu Jun 30 00:26:27 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
some_data=[[1,2],[3,4]]
some_data

[[1, 2], [3, 4]]

In [ ]:
type(some_data)

torch.Tensor

In [ ]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [ ]:
some_data=torch.tensor(some_data)

In [ ]:
some_data.dtype

torch.int64

In [ ]:
numpy_array=np.random.rand(3,4)

In [ ]:
numpy_array

array([[0.7591114 , 0.05901552, 0.00699274, 0.17629505],
       [0.32315599, 0.64232124, 0.14759223, 0.17900214],
       [0.59673414, 0.98283778, 0.87358274, 0.52874675]])

In [ ]:
torch.from_numpy(numpy_array)

tensor([[0.7591, 0.0590, 0.0070, 0.1763],
        [0.3232, 0.6423, 0.1476, 0.1790],
        [0.5967, 0.9828, 0.8736, 0.5287]], dtype=torch.float64)

In [ ]:
torch.tensor(numpy_array)

tensor([[0.7591, 0.0590, 0.0070, 0.1763],
        [0.3232, 0.6423, 0.1476, 0.1790],
        [0.5967, 0.9828, 0.8736, 0.5287]], dtype=torch.float64)

In [ ]:
my_tensor=torch.rand(3,4)


In [ ]:
my_tensor.device

device(type='cpu')

In [ ]:
my_tensor.matmul(my_tensor.T)

tensor([[1.3157, 1.7158, 0.2908],
        [1.7158, 2.6702, 0.5359],
        [0.2908, 0.5359, 0.1338]])

In [ ]:
torch.cat([my_tensor,my_tensor],axis=1)

tensor([[0.2381, 0.5300, 0.7595, 0.6335, 0.2381, 0.5300, 0.7595, 0.6335],
        [0.9352, 0.6105, 0.8083, 0.8772, 0.9352, 0.6105, 0.8083, 0.8772],
        [0.3032, 0.1359, 0.1381, 0.0658, 0.3032, 0.1359, 0.1381, 0.0658]])

In [ ]:
torch.nn.functional.softmax(my_tensor,dim=0)

tensor([[0.2454, 0.3626, 0.3865, 0.3518],
        [0.4927, 0.3930, 0.4058, 0.4488],
        [0.2619, 0.2445, 0.2076, 0.1994]])

In [ ]:
my_tensor.size()

torch.Size([3, 4])

In [ ]:
my_tensor.shape

torch.Size([3, 4])

In [ ]:
torch.rand(10,3,128,128)

In [ ]:
my_tensor.clip(0.2,0.8)

tensor([[0.2381, 0.5300, 0.7595, 0.6335],
        [0.8000, 0.6105, 0.8000, 0.8000],
        [0.3032, 0.2000, 0.2000, 0.2000]])

In [ ]:
a=torch.tensor([5.],requires_grad=True)
b=torch.tensor([6.],requires_grad=True)

In [ ]:
a

tensor([5.], requires_grad=True)

In [ ]:
y=a**3-b**2

In [ ]:
print(a.grad)

tensor([75.])


In [ ]:
y.backward()

In [ ]:
w= torch.randn(10,1,requires_grad=True)
b= torch.randn(1,requires_grad=True)

In [ ]:
w

tensor([[-0.3916],
        [ 0.4268],
        [-0.3572],
        [-1.3126],
        [ 0.4261],
        [ 1.8638],
        [-0.7678],
        [-0.1195],
        [-0.5626],
        [-1.2148]], requires_grad=True)

In [ ]:
x=torch.rand(1,10)
x

tensor([[0.5903, 0.9030, 0.4814, 0.3491, 0.0826, 0.4585, 0.6517, 0.1789, 0.2470,
         0.4364]])

In [ ]:
output= torch.matmul(x,w)+b

In [ ]:
output

tensor([[-0.3590]], grad_fn=<AddBackward0>)

In [ ]:
loss=1-output

In [ ]:
loss

tensor([[1.3590]], grad_fn=<RsubBackward1>)

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor([[-0.5903],
        [-0.9030],
        [-0.4814],
        [-0.3491],
        [-0.0826],
        [-0.4585],
        [-0.6517],
        [-0.1789],
        [-0.2470],
        [-0.4364]])

In [ ]:
with torch.no_grad():
  w= w- 0.001 *  w.grad.data

In [ ]:
w

tensor([[-0.3910],
        [ 0.4277],
        [-0.3568],
        [-1.3122],
        [ 0.4262],
        [ 1.8642],
        [-0.7672],
        [-0.1193],
        [-0.5623],
        [-1.2143]])

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
class CustomDataset:
  def __init__ (self,data,targets):
    self.data =data
    self.targets =targets
  def __len__ (self):
    return self.data.shape[0]
  def __getitem__ (self,idx):
    current_sample=self.data[idx,:]
    current_target =self.targets[idx]

    return {
        "sample":torch.tensor(current_sample,dtype=torch.float),
        "target":torch.tensor(current_target,dtype=torch.long),
    }


In [ ]:
data,targets =make_classification(n_samples=1000)

In [ ]:
data.shape

(1000, 20)

In [ ]:
custom_dataset=CustomDataset(data=data,targets=targets)

In [ ]:
len(custom_dataset)

1000

In [ ]:
custom_dataset[0]['sample']

tensor([-1.1359e+00,  4.3085e-01,  2.4694e-01, -7.8019e-01,  9.2284e-01,
        -3.5019e-02,  3.1634e-01,  1.2723e+00, -1.4738e+00, -3.4790e-02,
         2.3800e+00,  1.4211e+00,  1.4921e-03,  4.5660e-01,  8.1718e-01,
         1.3280e-01,  4.2136e-01,  5.1462e-01, -1.1086e+00, -3.3751e-01])

In [ ]:
for idx in range(len(custom_dataset)):
  print(custom_dataset[idx])

In [ ]:
#classification/regression
class CustomDataset:
  def __init__ (self,data,targets,tokenizer):
    self.data =data
    self.targets =targets
  def __len__ (self):
    return len(self.data)
  def __getitem__ (self,idx):
    text=self.data[idx,:]
    ent_target =self.targets[idx,:]
    current_target =self.targets[idx]
    input_ids= tokenizer(text)

    return {
        "text":torch.tensor(input_ids,dtype=torch.long),
        "target":torch.tensor(current_target,dtype=torch.long),
    }

In [ ]:
import torch
import cv2
import numpy

In [ ]:
class CustomDataset:
  def __init__ (self,image_paths,targets,augmentations):
    self.image_paths =image_paths
    self.targets =targets
    self.augmentations=augmentations
  def __len__ (self):
    return len(self.image_paths)
  def __getitem__ (self):
    target =self.targets[idx]
    image=cv2.imread(self.image_paths[idx])
    image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
    if self.augmentations is not None:
      augmented=self.augmentations(image=image)
      mask=augmented["mask"]
      #image=augmented["image"]
    image=np.transpose(image,(2,0,1)).astype(np.float32)
    return {
        "image":torch.tensor(image),
        "target":torch.tensor(target)
    }

In [ ]:
import torch
from sklearn.datasets import make_classification

In [ ]:
class CustomDataset:
  def __init__ (self,data,targets):
    self.data =data
    self.targets =targets
  def __len__ (self):
    return self.data.shape[0]
  def __getitem__ (self,idx):
    current_sample=self.data[idx,:]
    current_target =self.targets[idx]

    return {
        "x":torch.tensor(current_sample,dtype=torch.float),
        "y":torch.tensor(current_target,dtype=torch.long),
    }

In [ ]:
data,targets =make_classification(n_samples=1000)

In [ ]:
dataset=CustomDataset(data,targets)

In [ ]:
len(dataset)

1000

In [ ]:
train_loader=torch.utils.data.DataLoader(dataset,batch_size=4,num_workers=2)

In [ ]:
for data in train_loader:
  print(data['x'].shape)
  print(data['y'].shape)
  break

torch.Size([4, 20])
torch.Size([4])


In [ ]:
import torch
from sklearn.datasets import make_classification
class CustomDataset:
  def __init__ (self,data,targets):
    self.data =data
    self.targets =targets
  def __len__ (self):
    return self.data.shape[0]
  def __getitem__ (self,idx):
    current_sample=self.data[idx,:]
    current_target =self.targets[idx]

    return {
        "x":torch.tensor(current_sample,dtype=torch.float),
        "y":torch.tensor(current_target,dtype=torch.long),
    }

In [ ]:
data,targets =make_classification(n_samples=1000)
train_data,test_data,train_targets,test_targets=train_test_split(data,targets,stratify=targets)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_dataset=CustomDataset(train_data,train_targets)
test_dataset=CustomDataset(test_data,test_targets)

In [ ]:
train_loader=torch.utils.data.DataLoader(train_dataset,batch_size=4,num_workers=2)
test_loader=torch.utils.data.DataLoader(test_dataset,batch_size=4,num_workers=2)

In [ ]:
model=lambda x,w,b: torch.matmul(x,w) +b

In [ ]:
train_data.shape

(750, 20)

In [ ]:
from typing import Counter
W=torch.randn(20,1,requires_grad=True)
b=torch.randn(1,requires_grad=True)
learning_rate=0.001

for epoch in range(10):
    epoch_loss =0
    counter=0
    for data in train_loader:
      xtrain=data['x']
      ytrain=data['y']
      

      output=model(xtrain,W,b)
      loss=torch.mean((ytrain.view(-1)-output.view(-1))**2)
      epoch_loss =epoch_loss+loss.item()
      loss.backward()

      with torch.no_grad():
        W= W-learning_rate * W.grad
        b= b-learning_rate * b.grad

      W.requires_grad_(True)
      b.requires_grad_(True)
      counter+=1




    print(epoch,epoch_loss/counter)

0 14.252567946514551
1 5.031509960268406
2 2.1772478263270347
3 1.0398975198573255
4 0.5410846988472374
5 0.3140613885219902
6 0.20884976172547273
7 0.1595111589896136
8 0.13615239909206062
9 0.12499829214635959


In [ ]:
from sklearn import metrics

In [ ]:
outputs=[]
labels =[]
with torch.no_grad():
  for data in test_loader:
    xtest =data['x']
    ytest =data['y']

    output = model(xtest,W,b)
    labels.append(ytest)
    outputs.append(output)


In [ ]:
metrics.roc_auc_score(torch.cat(labels).view(-1),torch.cat(outputs).view(-1))

0.9373399897593446

In [ ]:
def train_one_step(model,data,optimizer):
  optimizer.zero_grad()
  for k,v in data.items():
    data[k]=v.to("cuda")
  loss= model(**data)
  #loss=model(x=data["x"],y=data["y"])
  loss.backward()
  optimizer.step()
  return loss
  


In [ ]:
def train_one_epoch(model,data_loader,optimizer,schedular):
  model.train()
  total_loss=0
  for batch_index,data in enumerate(data_loader):
    loss=train_one_step(model,data,optimizer)
    schedular.step()
    total_loss+=loss
  return total_loss

In [ ]:
def validate_one_step(model,data):
  for k,v in data.items():
    data[k]=v.to("cuda")
  loss= model(**data)
  return loss

In [ ]:
def validate_one_epoch(model,data_loader):
  model.train()
  total_loss=0
  for batch_index,data in enumerate(data_loader):
    with torch.no_grad():
       loss=validate_one_step(model,data)
    total_loss+=loss
  return total_loss